# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Build Linux
      run: dotnet publish -r linux-x64 -c Release -o ./publish/linux-x64/ --self-contained /p:PublishSingleFile=true
    - name: Build Windows
      run: dotnet publish -r win-x64 -c Release -o ./publish/win-x64/ --self-contained /p:PublishSingleFile=true
    - name: Upload a Linux Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: "dotcool.monitor-linux-x64-${{ github.ref }}-${{ github.run_id }}"
        path: ./publish/linux-x64/
    - name: Upload a Windows Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: "dotcool.monitor-windows-x64-${{ github.ref }}-${{ github.run_id }}"
        path: ./publish/win-x64/
          
