# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Build Linux
      run: dotnet publish ./dotCool.Monitor/dotCool.Monitor.csproj -r linux-x64 -c Release -o ./publish/linux-x64/ --self-contained /p:PublishSingleFile=true
    - name: Build Windows
      run: dotnet publish ./dotCool.Monitor/dotCool.Monitor.csproj -r win-x64 -c Release -o ./publish/win-x64/ --self-contained /p:PublishSingleFile=true /p:EnableWindowsTargeting=true /p:IncludeNativeLibrariesForSelfExtract=True /p:StaticWebAssetsEnabled=False
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch
    - name: Upload a Linux Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: "dotcool.monitor-linux-x64-${{ steps.extract_branch.outputs.branch }}-${{ github.run_id }}"
        path: ./publish/linux-x64/
    - name: Upload a Windows Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: "dotcool.monitor-windows-x64-${{ steps.extract_branch.outputs.branch }}-${{ github.run_id }}"
        path: ./publish/win-x64/
          
