name: Create release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-latest
    steps:
      - name: Grab latest build id
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          workflow: dotnet.yml
          branch: ${{ github.ref_name }}
        id: extract_run_id
        run: echo "run_id=$(gh run list -c '$pr_head_sha' -w '$workflow' -b '$branch' -L 1 --json databaseId --jq '.[0].databaseId')" >> $GITHUB_OUTPUT
      - name: Download build artifacts
        uses: actions/download-artifact@v4.3.0
        with:
          path: ./artifacts
          # A glob pattern matching the artifacts that should be downloaded. Ignored if name is specified.
          pattern: "dotcool.monitor-windows-x64-${{ steps.extract_branch.outputs.branch }}*"
          run_id: ${{ steps.extract_run_id.outputs.run_id }}
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag#v}" \
              --draft=true \
              --prerelease=true
      
      - name: Upload Release Artifacts
        uses: chihqiang/upload-asset-action@v0.1.0
        with:
          # GitHub Token with `repo` scope
          github_token: ${GITHUB_TOKEN}
          # List of files to upload, separated by space
          files: ./artifacts
